services:
    datastore:
        build: ./datastore
        entrypoint: /datastore
        ports:
            - "8081:8081"

    wrapper:
        build: ./opawrap
        entrypoint:
            - /opawrap
            - /policies/counter.rego # or /policies/comm.rego
        ports:
            - "8080:8080"
        volumes:
            - ./policies/:/policies/
        environment:
            - DATASTORE_URL=datastore
        depends_on:
            - datastore
